version: '3.8'

services:
  fig-api:
#    image: fig.api:latest
    image: mzbrau/fig-api:latest
#    build:
#      context: .
#      dockerfile: src/api/Fig.Api/Dockerfile
    ports:
      - "7281:80"
    environment:
      - ApiSettings:DbConnectionString=Server=${fqdn};User Id=fig;Password=fig_secret;Initial Catalog=fig
      - no_proxy=fig-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fig-api:80/_health"]
      interval: 5s
      timeout: 10s
      retries: 3

  fig-web:
#    image: fig.web:latest
    image: mzbrau/fig-web:latest
#    build:
#      context: .
#      dockerfile: src/web/Fig.Web/Dockerfile
    ports:
      - "7148:80"
    depends_on:
      fig-api:
        condition: service_healthy
    environment:
      - no_proxy=fig-api
