name: "Deploy to Docker"

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Web
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/web/Fig.Web/Dockerfile
          push: true
          tags: mzbrau/fig-web:latest

      - name: Build and push Api
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/api/Fig.Api/Dockerfile
          push: true
          tags: mzbrau/fig-api:latest