# The name of the workflow.
# This is the name that's displayed for status
# badges (commonly embedded in README.md files).
name: create pre-release

# Trigger this workflow on a push, or pull request to
# the main branch, when either C# or project files changed
on:
  push:
    tags:
      - "*-alpha"

# Create an environment variable named DOTNET_VERSION
# and set it as "7.0.x"
env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

# Defines a single job named "build-and-test"
jobs:
  build-and-test:

    # When the workflow runs, this is the name that is logged
    # This job will run three times, once for each "os" defined
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [windows-latest]

    # Each job run contains these five steps
    steps:

    # 1) Check out the source code so that the workflow can access it.
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # 2) Set up the .NET CLI environment for the workflow to use.
    #    The .NET version is specified by the environment variable.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # 3) Restore the dependencies and tools of a project or solution.
    - name: Install dependencies
      run: dotnet restore ./src

    # 4) Build a project or solution and all of its dependencies.
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src

    # 5) Test a project or solution.
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" ./src 

    - name: Publish Api
      run: dotnet publish ./src/api/Fig.Api/Fig.Api.csproj --runtime win-x64 --configuration Release --self-contained true -p:PublishSingleFile=true -p:PublishedTrimmed=true -p:IncludeAllContentForSelfExtract=true

    - name: Zip API
      uses: papeloto/action-zip@v1
      with:
        files: ./src/api/Fig.Api/bin/Release/net7.0/win-x64/publish
        dest: ./src/api/Fig.Api/bin/Release/net7.0/win-x64/Fig.Api.zip

    - name: Publish Web
      run: dotnet publish ./src/web/Fig.Web/Fig.Web.csproj --runtime win-x64 --configuration Release --self-contained true -p:PublishedTrimmed=true -p:IncludeAllContentForSelfExtract=true

    - name: Zip Web
      uses: papeloto/action-zip@v1
      with:
        files: ./src/web/Fig.Web/bin/Release/net7.0/win-x64/publish
        dest: ./src/web/Fig.Web/bin/Release/net7.0/win-x64/Fig.Web.zip

    - name: createRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create ${{ github.ref_name }} --generate-notes ./src/api/Fig.Api/bin/Release/net7.0/win-x64/Fig.Api.zip ./src/web/Fig.Web/bin/Release/net7.0/win-x64/Fig.Web.zip
